### ISSUE TITLE
네트워크 상태 모니터링 기술 분석

### ISSUE THREAD

**Issue by kokids** [kokids/kisti#14]
snmp, nagios, cacti 플러그인 기능 분석

**Comment by dsp518** [comment]
**nagios plugin의 역할은 다음 두가지로 나눌 수 있다.**
•Host로부터 정보를 가져온다. (예, CPU 로드, index.html)
•Host의 특정 상태나 비교 결과를 exit code로 반환한다.

**Comment by dsp518** [comment]
**SNMP( simple network management protocol)**
TCP/IP 기반의 네트워크에서 네트워크 상의 각 호스트에서 정기적으로 여러 가지 정보를 자동적으로 수집하여 네트워크 관리를 하기 위한 프로토콜


**Nagios**
Nagios 이라는 모니터링 툴은 서버, 네트워크 장비를 포함하여 HTTP,
FTP, SMTP 같은 서비스를 모니터링 하고 장애가 발생하면 관리자에게 메일이나
SMS로 알려준다. 또한 Web UI를 통해서 한 눈에 시스템 상태를 볼 수도 있다.

하지만 Nagios는 오픈소스이기 때문에 스스로 소스를 내려 받아 컴파일하고 설치
해야 하며 원하는 모니터링을 위한 설정을 하나하나 해야 한다. 또한 아래의 장점
을 가지고 있지만, Graph 생성을 하지 못하는 단점을 가지고 있다. 그리하여
Cacti에 plugin으로 추가하여 툴의 장점을 최대한 사용하도록 한다.

1) Monitor your entire IT infrastructure
2) Spot problems before they occur
3) Know immediately when problems arise
4) Share availability data with stakeholders
5) Detect security breaches
6) Plan and budget for IT upgrades
7) Reduce downtime and business losses


**Cacti**
Cacti는 RRD Tool과 SNMP를 기반으로 한 네트워크 모니터링 Tool로
APM(Apache, PHP, Mysql)과 연계하여 네트워크를 모니터링하여 관리상의 편의
를 제공한다. 오픈소스 프로그램이며, 처음에 접근이 어려울 수 있지만 익숙해질
수록 유연하게 사용할 수 있는 장점이 있다. 또한 RRD Tool을 이용하여 깔끔한
그래프를 생성 가능하며, xml 형태의 양식을 제공하여 RRD 활용을 극대화하며
다양한 Plugin을 추가하여 상용 NMS의 기능에 근접하게 기능을 확장할 수 있다.

**Comment by dsp518** [comment]
**네트워크 모니터링 기능**
 Cacti 툴은 Ping, SNMP를 기반으로 네트워크 상태 모
니터링 기능을 수행하며, Traffic Graph와 Monitoring Alert 기능으로 상시 모니
터링이 가능하다. 또한 주기적인 Ping Check를 통하여 장애 발생시 Mail Alert
기능으로 사용자가 신속하게 대처 할 수 있도록 한다. [그림 25]과 같이 현재 네
트워크 상태를 등록된 Mail 주소로 알려준다.

**Comment by kokids** [comment]
이 Task의 완료일이 오늘(6/17 금)입니다. 완료되면 관련 자료 등록 후(있으실 경우) 완료 처리해주세요.

[--- Commented from Asana.com
#commenter 박주연
---[aa]

**Comment by kokids** [comment]
현재 Cacti와 Nagios에 대하여 기능확인 중이며 이번 주중으로 자료 업로드 후 완료 처리 할 예정입니다.

[--- Commented from Asana.com
#commenter TAEYUL KIM
---[aa]

**Comment by kokids** [comment]
네트워크 모니터링 툴에 대한 비교 자료를 업로드합니다.

[--- Commented from Asana.com
#commenter TAEYUL KIM
---[aa]
